<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.16</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.jclinical</groupId>
    <artifactId>clinerya-parent</artifactId>
    <version>0.10.0-beta.1</version>
    <packaging>pom</packaging>

    <name>clinerya-parent</name>
    <description>Proyecto Clinerya - Arquitectura Hexagonal</description>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mapstruct.version>1.6.0</mapstruct.version>
        <lombok.version>1.18.34</lombok.version>

        <!-- SonarCloud Properties -->
        <sonar.organization>julio-cuellar</sonar.organization>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
        <sonar.projectKey>Julio-Cuellar_medicloud</sonar.projectKey>
        <sonar.coverage.jacoco.xmlReportPaths>**/target/site/jacoco/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
    </properties>

    <modules>
        <module>clinerya-core</module>
        <module>clinerya-messaging</module>
        <module>clinerya-users</module>
        <module>clinerya-staff</module>
        <module>clinerya-clinics</module>
        <module>clinerya-auth</module>
        <module>clinerya-patients</module>
        <module>clinerya-records</module>
        <module>clinerya-attachments</module>
        <module>clinerya-inventory</module>
        <module>clinerya-treatments</module>
        <module>clinerya-agenda</module>
        <module>clinerya-integrations</module>
        <module>clinerya-cash</module>
        <module>clinerya-accounting</module>
        <module>clinerya-notifications</module>
        <module>clinerya-collaboration</module>
        <module>clinerya-app</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- Módulos Internos -->
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-users-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-users-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-clinics-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-clinics-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-staff-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-staff-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-app</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-auth-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-auth-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-patients-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-patients-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-records-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-records-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-attachments</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-inventory-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-inventory-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-treatments-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-treatments-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-agenda-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-agenda-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-integrations-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-integrations-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-cash-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-cash-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-messaging</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-accounting-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-accounting-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-notifications-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-notifications-infra</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-collaboration-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.jclinical</groupId>
                <artifactId>clinerya-collaboration-infra</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- MapStruct -->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok-mapstruct-binding</artifactId>
                                <version>0.2.0</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
