package com.jclinical.core.security;

import java.util.EnumSet;
import java.util.Set;

public enum StaffPermission {
    VIEW_DASHBOARD,
    VIEW_DASHBOARD_METRICS,
    VIEW_OPERATIONAL_ALERTS,
    VIEW_NOTIFICATIONS,
    MANAGE_AGENDA,
    VIEW_AGENDA,
    CREATE_APPOINTMENTS,
    EDIT_APPOINTMENTS,
    CANCEL_APPOINTMENTS,
    MANAGE_WAITING_LIST,
    MANAGE_SCHEDULES,
    MANAGE_ROOMS,
    VIEW_ROOMS,
    CREATE_ROOMS,
    EDIT_ROOMS,
    ASSIGN_ROOM_STAFF,
    VIEW_PATIENT_CARE,
    MANAGE_PATIENT_CARE,
    CREATE_VISITS,
    EDIT_VISITS,
    MANAGE_PRESCRIPTIONS,
    MANAGE_PATIENTS,
    VIEW_PATIENTS,
    CREATE_PATIENTS,
    EDIT_PATIENTS,
    EXPORT_PATIENTS,
    VIEW_MEDICAL_RECORDS,
    EDIT_MEDICAL_RECORDS,
    CREATE_CLINICAL_NOTES,
    EDIT_CLINICAL_NOTES,
    VIEW_RECORD_DOCUMENTS,
    MANAGE_RECORD_TEMPLATES,
    MANAGE_TREATMENTS,
    VIEW_TREATMENTS,
    MANAGE_TREATMENT_CATALOG,
    MANAGE_QUOTATIONS,
    MANAGE_PROCEDURES,
    REGISTER_TREATMENT_SALES,
    MANAGE_CASH,
    VIEW_CASH,
    CREATE_CHARGES,
    MANAGE_REFUNDS,
    MANAGE_CASH_CUTS,
    MANAGE_EXPENSES,
    MANAGE_INVENTORY,
    VIEW_INVENTORY,
    MANAGE_MATERIALS,
    MANAGE_PURCHASES,
    MANAGE_INVENTORY_MOVEMENTS,
    MANAGE_INVENTORY_LOTS,
    VIEW_ACCOUNTING,
    MANAGE_ACCOUNTING,
    VIEW_JOURNAL_ENTRIES,
    CREATE_JOURNAL_ENTRIES,
    VIEW_FINANCIAL_REPORTS,
    MANAGE_BANK_ACCOUNTS,
    MANAGE_STAFF,
    VIEW_STAFF,
    MANAGE_STAFF_PERMISSIONS,
    MANAGE_ATTENDANCE,
    MANAGE_STAFF_ACTIVITY,
    MANAGE_CLINIC,
    VIEW_CLINIC_SETTINGS,
    MANAGE_INTEGRATIONS,
    MANAGE_CLINIC_BACKUPS,
    MANAGE_PAYROLL,
    VIEW_PAYROLL;

    /**
     * Permisos que tocan la atencion de un paciente: expediente, notas, recetas, visitas y
     * presupuestos. Un administrador solo los tiene si ademas atiende pacientes; el catalogo de
     * tratamientos y las plantillas de historia quedan fuera porque son configuracion.
     */
    public static final Set<StaffPermission> CLINICAL = EnumSet.of(
            VIEW_MEDICAL_RECORDS,
            EDIT_MEDICAL_RECORDS,
            CREATE_CLINICAL_NOTES,
            EDIT_CLINICAL_NOTES,
            VIEW_RECORD_DOCUMENTS,
            VIEW_PATIENT_CARE,
            MANAGE_PATIENT_CARE,
            CREATE_VISITS,
            EDIT_VISITS,
            MANAGE_PRESCRIPTIONS,
            MANAGE_TREATMENTS,
            MANAGE_QUOTATIONS,
            MANAGE_PROCEDURES);

    public boolean isClinical() {
        return CLINICAL.contains(this);
    }
}
